apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.30.0
    created: "2025-04-06T03:10:52.294643993Z"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: 532bb69ca53bad3deaea24e29fff85c9f112c456fc8399e4a802e3dbc5f849a7
    home: https://bitnami.com
    icon: https://dyltqmyl993wv.cloudfront.net/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/common
    type: library
    urls:
    - https://MAFKarlos.github.io/LiteLLM/charts/common-2.30.0.tgz
    version: 2.30.0
  litellm-helm:
  - apiVersion: v2
    appVersion: v1.63.11-stable.patch1
    created: "2025-04-06T03:10:52.305864978Z"
    dependencies:
    - condition: db.deployStandalone
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: '>=13.3.0'
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: '>=18.0.0'
    description: Call all LLM APIs using the OpenAI format
    digest: 636dd3a1ad7029a9205d8cafdd1ade2293956415bb58d1b55c36f4784f91e873
    name: litellm-helm
    type: application
    urls:
    - https://MAFKarlos.github.io/LiteLLM/charts/litellm-helm-0.1.639.tgz
    version: 0.1.639
generated: "2025-04-06T03:10:52.293867574Z"
